<script setup lang="ts">
import {computed} from 'vue'
import {withBase} from 'vitepress'
import type {TaskPage} from '../../../../src/research/site'
import {taskStatus,phaseNames} from '../../../../src/research/site'
import EvidenceList from './EvidenceList.vue'
import AgricultureTaskFollowups from './AgricultureTaskFollowups.vue'
import {evidenceLevelNames,evidenceDateNames} from '../../../../src/research/evidence-labels'
const props=defineProps<{record:TaskPage}>()
const t=computed(()=>props.record.task)
const stages={'not-applicable':'背景／规范','vendor-report':'厂商自报',laboratory:'实验室',pilot:'试点','commercial-operation':'持续商业运行',unknown:'阶段不明'}
const conditionNames:Record<string,string>={'no-retained-matching-mechanism-after-task-search':'本轮任务检索未保留匹配机制，适用方案仍待验证','partial-or-adjacent-mechanism-only':'仅有局部或相邻流程机制，需核验目标对象与完整验收'}
const kinds={fact:'直接事实',calculation:'计算结果',judgment:'研究判断',hypothesis:'待验证假设'}
const alternativeNames={'traditional-machine':'传统机械','dedicated-machine':'专机',robot:'机器人','assistive-tool':'辅助工具','digital-process':'数字流程',unclassified:'类别待核'}
const barrierNames={technical:'技术条件',economic:'经济参数',adoption:'采用与分工'}
const publicResearch=computed(()=>t.value.dossier?.publicResearch as Record<string,any>|undefined)
const claim=(id:string)=>props.record.claims.find(c=>c.id===id)
const conclusionEvidence=computed(()=>[...new Map(t.value.conclusionIds.flatMap(id=>claim(id)?.evidence??[]).map(r=>[r.sourceId+'|'+r.locator,r])).values()])
const researchDates=computed(()=>props.record.sources.filter(s=>s.evidenceLevel).map(s=>({id:s.id,title:s.title,period:[s.evidencePeriod??'未注明资料时期','发布日期：'+(s.publishedLabel??s.published??'未确认'),...(s.dates??[]).map(d=>evidenceDateNames[d.kind]+'：'+d.value)].join(' · ')})))
</script>
<template>
 <article class="task-view" :data-country="t.country">
  <nav class="breadcrumbs"><a :href="withBase('/'+t.country+'/')">{{t.country==='cn'?'中国':'美国'}}</a><span> / </span><a :href="withBase('/'+t.country+'/industries/'+t.industryId)">{{record.industry.name}}</a></nav>
  <p class="eyebrow">{{record.scenario.title}} · {{phaseNames[t.phase]}}</p>
  <h1 :data-content-id="t.id+'-title'" tabindex="0">{{t.title}}</h1>
  <AgricultureTaskFollowups :record="record"/>
  <section class="task-conclusion" :data-content-id="t.id+'-conclusion'" tabindex="0"><span class="tag">{{taskStatus[t.researchStatus]}}</span><p><strong v-if="t.dossier?.agricultureFollowups">首轮结论：</strong>{{t.summary}}</p><p v-if="t.researchStatus==='not-started'" class="scope-note">本页是任务发现记录。尚未完成自动化及反例检索，不能据此判断方案不可行或没有商业案例。</p><template v-if="publicResearch"><p class="scope-note">已执行本定义的正向与反向查询并完成原稿独立审校；任务拆分和双路径核查仍在继续。以下结论保留适用条件，当前未冻结。</p><ul class="historical-note"><li v-for="s in researchDates">{{s.title}}：{{s.period}}</li></ul><EvidenceList v-if="conclusionEvidence.length" :items="conclusionEvidence"/></template></section>
  <section v-if="publicResearch?.definitionReview" class="work-note" :data-content-id="t.id+'-definition-review'" tabindex="0"><h2>任务边界与独立复核</h2><p>{{publicResearch.definitionReview.note}}</p><p v-if="publicResearch.definitionReview.proposedDecomposition&&!publicResearch.definitionReview.children?.length">当前条目仍包含需要分别研究的动作，具体子任务待进一步定义，不计为新增已研究任务。</p><p v-if="publicResearch.definitionReview.children?.length">拟议拆分如下；这些子项尚未分别完成证据核查，不计为新增已研究任务。</p><ul><li v-for="title in publicResearch.definitionReview.children">{{title}}</li></ul></section>
  <section :data-content-id="t.id+'-boundary'" tabindex="0"><h2>执行范围与验收定义</h2><p>{{t.boundary}}</p><p class="scope-note">{{t.discovery?.acceptanceStatus}}</p><p><strong>输入：</strong>{{t.inputs.join('；')}}</p><p><strong>输出：</strong>{{t.outputs.join('；')}}</p><ul><li v-for="a in t.acceptance">{{a}}</li></ul></section>
  <section :data-content-id="t.id+'-discovery'" tabindex="0"><h2>任务发现依据</h2><p class="scope-note">原始编号 {{t.discovery?.originalId}}。来源支持程度和拆分建议仍可能在独立审查中修订；职业描述不证明实际工时或人工占比。</p><details open><summary>流程规范路径</summary><EvidenceList v-if="t.workflowEvidence.length" :items="t.workflowEvidence"/><p v-else>尚未取得绑定到本任务的流程依据。</p></details><details open><summary>职业职责路径</summary><EvidenceList v-if="t.occupationEvidence.length" :items="t.occupationEvidence"/><p v-else>尚未取得绑定到本任务的职业职责依据。</p></details><div v-if="t.discovery?.sourceLimitations.length" class="historical-note"><strong>使用资料的年份与适用限制</strong><ul><li v-for="text in t.discovery.sourceLimitations">{{text}}</li></ul></div></section>
  <section :data-content-id="t.id+'-alternatives'" tabindex="0"><h2>替代方案与残留人工</h2><p v-if="!t.alternatives.length">尚未完成传统机械、专机、机器人、辅助工具与必要数字流程的逐项比较。残留人工及部署阶段仍缺证据。</p><article v-for="(a,i) in t.alternatives" :key="i" :data-content-id="t.id+'-alternative-'+i" tabindex="0"><h3>{{alternativeNames[a.category]}}</h3><p>{{a.description}}</p><template v-for="id in a.claimIds"><p v-if="claim(id)&&claim(id)!.text!==a.description"><span class="tag">{{kinds[claim(id)!.kind]}}</span> {{claim(id)!.text}}</p><EvidenceList v-if="claim(id)?.evidence.length" :items="claim(id)!.evidence"/></template><p>条件：{{a.conditions.map(text=>conditionNames[text]??text).join('；')}}</p><p>残留人工与未证实替代范围：{{a.remainingLabor.join('；')}}</p></article><details v-if="publicResearch?.deploymentEvidence?.length"><summary>部署阶段与证据范围</summary><ul><li v-for="d in publicResearch.deploymentEvidence">{{evidenceLevelNames[d.level]??d.level}}：{{d.scope}}。未确认完整任务持续商业运行。<EvidenceList :items="[{sourceId:d.sourceId,locator:d.locator}]"/></li></ul></details></section>
  <section :data-content-id="t.id+'-barriers'" tabindex="0"><h2>障碍与反例检查</h2><p v-if="!t.barriers.length">技术、经济与采用障碍尚未完成场景化研究；失败、退出、未采用和成功反例均待逐项核查。</p><p v-if="publicResearch" class="scope-note">{{publicResearch.technicalQuestionPolicy}}</p><article v-for="(b,i) in t.barriers" :data-content-id="t.id+'-barrier-'+i" tabindex="0"><h3>{{barrierNames[b.type]}}</h3><template v-for="id in b.claimIds"><p v-if="claim(id)">{{kinds[claim(id)!.kind]}}：{{claim(id)!.text}}</p><EvidenceList v-if="claim(id)?.evidence.length" :items="claim(id)!.evidence"/></template></article><div v-if="publicResearch" :data-content-id="t.id+'-counterevidence'" tabindex="0"><h3>失败、退出、未采用及成功反例</h3><p>已执行本任务的反向查询。当前未取得可独立验证的完整任务持续商业运行成功反例；未找到匹配失败案例也不能证明没有失败或技术不可行。</p><template v-for="id in t.counterevidenceIds"><p>{{claim(id)?.text}}</p><EvidenceList v-if="claim(id)?.evidence.length" :items="claim(id)!.evidence"/></template><p v-if="!t.counterevidenceIds.length">本轮没有选入具备原文定位的匹配失败、退出或未采用案例，仍需现场访谈与运行记录。</p></div></section>
  <section :data-content-id="t.id+'-economics'" tabindex="0"><h2>人工投入与回报</h2><p class="work-note">尚未取得完整增量现金流参数，不计算回收期。币种为 {{t.country==='cn'?'人民币 CNY':'美元 USD'}}。</p><dl><template v-for="m in t.manualInputs"><dt>{{m.name}}</dt><dd>{{m.value??'缺失'}} · {{m.unit}}<p>{{m.gap}}</p><EvidenceList v-if="m.evidence.length" :items="m.evidence"/></dd></template></dl><details v-if="publicResearch?.economics"><summary>增量现金流口径与缺少的参数</summary><p>期初投入包含设备、场地改造、集成、培训、调试和初始营运资金。逐期现金流从可实际取消的现金人工和有需求依据的增产贡献出发，扣除残留人工、维护耗材、异常返工停机、服务费、税费和营运资金变化。</p><p>{{publicResearch.economics.workingCapitalDefinition}}</p><p>{{publicResearch.economics.throughputBenefitConstraint}}</p><p>{{publicResearch.economics.comparisonScope}}</p></details></section>
  <section v-if="record.claims.length" :data-content-id="t.id+'-claims'" tabindex="0"><h2>结论与证据</h2><details v-for="c in record.claims" :key="c.id" :data-content-id="c.id" tabindex="0"><summary>{{kinds[c.kind]}} · {{c.text}}</summary><p>{{stages[c.deployment]}} · {{c.conditions.join('；')}}</p><EvidenceList :items="c.evidence"/></details></section>
  <section :data-content-id="t.id+'-gaps'" tabindex="0"><h2>证据缺口</h2><p v-if="t.dossier?.agricultureFollowups" class="scope-note">以下保留首轮缺口记录。其中补检审查已完成的范围，以本页开头的补充研究为准；尚待现场验证的缺口继续开放。</p><ul><li v-for="g in t.evidenceGaps">{{g}}</li></ul></section>
  <section :data-content-id="t.id+'-interviews'" tabindex="0"><h2>待访谈问题</h2><ol><li v-for="q in t.interviewQuestions">{{q}}</li></ol></section>
  <details v-if="record.searches.length" :data-content-id="t.id+'-searches'" tabindex="0"><summary>本任务的检索记录</summary><p>首轮研究记录：{{publicResearch?.searchSummary}}</p><p v-if="t.dossier?.agricultureFollowups">本次农业补检已经独立审校并追加；上方“补充研究与边界更新”展示最新结果。以下逐条查询保留各自的范围和审计依据。</p><ol><li v-for="s in record.searches"><strong>{{s.direction==='automation'?'方案与成功条件':'失败、退出及未采用'}} · {{s.searchedOn}}</strong><p>{{s.query}}</p><p>{{s.note}}</p><a v-if="s.audit" :href="'https://github.com/JoenHune/labor-automation-atlas/blob/main/'+s.audit.file" target="_blank" rel="noopener noreferrer">查看查询与筛选审计</a></li></ol></details>
  <p class="scope-note">研究版本 {{record.version}} · {{record.checkedAt}}。当前未冻结；评论不会自动成为研究事实。</p>
  <a :href="withBase('/exports/'+t.id+'.json')" download>导出本任务、来源与检索记录</a>
 </article>
</template>
